---

- name: "Ensures {{ ca_defult_ssl_certs_dir }} and {{ ca_defult_ssl_key_dir }} dirs exist"
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0750
    recurse: yes
  with_items:
  - "{{ ca_defult_ssl_certs_dir }}"
  - "{{ ca_defult_ssl_key_dir }}"

- name: "Distribute inventory_hostname-priv-key.pem to inventory_hostname"
  copy: src="{{ ca_distribution_certs_dir }}/{{ inventory_hostname }}-priv-key.pem" dest="{{ ca_defult_ssl_key_dir }}/{{ inventory_hostname }}-priv-key.pem"

- name: "Distribute inventory_hostname-cert.pem to inventory_hostname"
  copy: src="{{ ca_distribution_certs_dir }}/{{ inventory_hostname }}-cert.pem" dest="{{ ca_defult_ssl_certs_dir }}/{{ inventory_hostname }}-cert.pem"


# Root CA key/cert

- name: "copy {{ ca_key }} to {{ ca_defult_ssl_key_dir }}"
  copy:
    src: "{{ ca_distribution_certs_dir }}/{{ item }}"
    dest: "{{ ca_defult_ssl_key_dir }}/{{ item }}"
  with_items:
  - "{{ ca_key }}"

- name: "copy {{ ca_cert }} to {{ ca_defult_ssl_certs_dir }}"
  copy:
    src: "{{ ca_distribution_certs_dir }}/{{ item }}"
    dest: "{{ ca_defult_ssl_certs_dir }}/{{ item }}"
  with_items:
  - "{{ ca_cert }}"

- shell: "ls -lR {{ item }}"
  with_items:
  - "{{ ca_defult_ssl_key_dir }}/{{ inventory_hostname }}-priv-key.pem"
  - "{{ ca_defult_ssl_certs_dir }}/{{ inventory_hostname }}-cert.pem"
  register: ls
  when: debug is defined

- debug: var=item.stdout_lines
  with_items:
  - "{{ ls.results }}"
  when: debug is defined
