---
- stat:
    path: "{{ shelleg.ca_distribution_certs_dir}}/{{ item }}-priv-key.pem"
  with_inventory_hostnames: all:!localhost
  register: key_stat

- stat:
    path: "{{ shelleg.ca_distribution_certs_dir}}/{{ item }}-cert.pem"
  with_inventory_hostnames: all:!localhost
  register: cert_stat

#- fail:
#    msg: "Looks like {{ item.stat.path }} doesn't exist"
#  when: item.stat.exists != true
#  with_items: "{{ cert_stat.results }}"
#  register: cert_out
#
#- fail:
#    msg: "Looks like {{ item.stat.path }} doesn't exist"
#  when: item.stat.exists != true
#  with_items: "{{ key_stat.results }}"
#  register: key_out

- debug:
    msg: "Looks like {{ item.stat.path }} exist"
  when: item.stat.exists == true
  with_items: "{{ cert_stat.results }}"
  register: cert_out

- debug:
    msg: "Looks like {{ item.stat.path }} exist"
  when: item.stat.exists == true
  with_items: "{{ key_stat.results }}"
  register: key_out

- debug:
    msg: "seems all keys are in place"
  when: key_out.changed == false

- debug:
    msg: "seems all certs are in place"
  when: cert_out.changed == false