---
- hosts: localhost
  vars:
    create_swarm: true
    vagrant: true
    aws: false
  roles:
    - role: infra-init
      tags: init

- hosts: swarm-instances
  become: yes
  become_user: root
  vars:
    ca_distribute_keys: true
  roles:
    - role: common # shellg common tasks
      tags: always
    - role: ntp
      tags: core,ntp
    - role: ca
      tags: ca,core
    - role: apt-cacher-ng   # become apt-cacher client
      tags: core
    - role: ansible-role-docker-swarm
      tags: code,swarm
    - role: dnsmasq         # configure to use dnsmasq as dns
      tags: code,dns
    - role: docker-registrator
      tags: registrator
#    - role: nfs
#      tags: init,nfs


- hosts: swarm-manager-instances
  become: yes
  become_user: root
  roles:
    - role: swarm-visualizer
      tags: swarm,visualizer